import dotenv from "dotenv";
dotenv.config();

const constants = Object.freeze({
  CONST_APP_NAME: process.env.APP_NAME,
  CONST_APP_URL: process.env.APP_URL,
  CONST_APP_VERSION: process.env.APP_VERSION,

  CONST_JWT_TOKEN_KEY: process.env.JWT_TOKEN_KEY,

  // API Response code
  CONST_RESP_CODE_OK: 200,
  CONST_RESP_CODE_CREATED: 200,
  CONST_RESP_CODE_CONTENT_NOT_FOUND: 200,
  CONST_RESP_CODE_DATA_NOT_MODIFIED: 200,
  CONST_RESP_CODE_BAD_REQUEST: 200,
  CONST_RESP_CODE_UNAUTHORIZED: 200,
  CONST_RESP_CODE_NOT_FOUND: 200,
  CONST_RESP_CODE_NOT_ACCEPT: 200,
  CONST_RESP_CODE_INTERNAL_SERVER_ERROR: 500,

  CONST_USER_VERIFIED_TRUE: true,
  CONST_USER_VERIFIED_FALSE: false,

  CONST_GEN_SALT: 10,
  CONST_DB_URL: process.env.MONGODB_URL,

  CONST_ROLE_ADMIN: 1,
  CONST_ROLE_USER: 2,

  CONST_APP_PROFILE_IMG: "profile-image/",
  CONST_APP_ICON_IMG: "icon/",
  CONST_APP_VEDIO: "vedio/",
  CONST_APP_VEDIO_IMAGE: "images/",

  CONST_TRIP_SOLO: 1,
  CONST_TRIP_GROUP: 2,

  CONST_PAGE: 1,
  CONST_LIMIT: 10,

  CONST_RESP_LANG_COLLECTION: ["en"],

  CONST_VALIDATE_SESSION_EXPIRE: "24h",

  CONST_STATUS_ACTIVE: "Active",
  CONST_STATUS_INACTIVE: "In-Active",
  CONST_STATUS_IGNORE: "Ignore",
  CONST_STATUS_COMPLETED: "Completed",
  CONST_STATUS_CANCELLED: "Cancelled",
  CONST_STATUS_ACCEPT: "Accept",
  CONST_STATUS_PENDING: "Pending",
  CONST_STATUS_SUCCESS: "Success",
  CONST_STATUS_FAILED: "Failed",
  CONST_STATUS_DELETED: "Deleted",
  CONST_STATUS_REFUNDED: "Refunded",
  CONST_STATUS_REJECTED: "Rejected",
  CONST_STATUS_NOT_APPLICABLE: "Not-Applicable",
  CONST_STATUS_NOT_ATTEMPT: "Not Attempted",
  CONST_STATUS_BLOCK: "Block",
  CONST_STATUS_UNBLOCK: "Unblock",
  CONST_STATUS_APPROVED: "Approved",

  CONST_FORGOT_OTP: "forgotPassword",
  CONST_REGISTER_OTP: "registerOtp",

  CONST_DEVICE_TYPES: ["ios", "android", "browser"],
  CONST_DEVICE_ANDROID: "Android",
  CONST_DEVICE_IOS: "Ios",
  CONST_DEVICE_BROWSER: "Browser",

  CONST_WEB_ADMIN: "Admin",
  CONST_WEB_USER: "User",
  CONST_SELF: "Self",

  CONST_ALLOW_URL_WITHOUT_HEADER: ["/", "/api-admin/"],

  CONST_SMTP_HOST: process.env.MAIL_HOST,
  CONST_SMTP_PORT: process.env.MAIL_PORT,
  CONST_SMTP_USER: process.env.MAIL_USERNAME,
  CONST_SMTP_PASSWORD: process.env.MAIL_PASSWORD,
  CONST_SMTP_FROM_ADDRESS: process.env.MAIL_FROM_ADDRESS,

  AWS_S3_BUCKET_NAME: process.env.ENV_AWS_S3_BUCKET_NAME,
  AWS_S3_BUCKET_ACCESS_ID: process.env.ENV_AWS_S3_BUCKET_ACCESS_ID,
  AWS_S3_BUCKET_SECRET_ID: process.env.ENV_AWS_S3_BUCKET_SECRET_ID,
  AWS_S3_BUCKET_URL: process.env.ENV_AWS_S3_BUCKET_URL,
  AWS_S3_BUCKET_REGION: process.env.ENV_AWS_S3_BUCKET_REGION,

  CONST_USER_IMAGE: process.env.USER_DEFAULT_IMAGE,

  CONST_SERVER_KEY: process.env.SERVER_KEY,

  CONST_GENDER_MALE: 1,
  CONST_GENDER_FEMALE: 2,

  CONST_SUBSCRIPTION_NOMAD: "capri_nomad",
  CONST_SUBSCRIPTION_MATCH: "capri_match",
  CONST_SUBSCRIPTION_BOTH: "capri_both",
  CONST_SUBSCRIPTION_NONE:"capri_none",

  CONST_DUMMY_IMAGE:
    "https://smbc-app.s3.eu-west-3.amazonaws.com/profile-image/1725942573368.png",
  CONST_APP_LOGO:
    "https://epasu.s3.us-east-1.amazonaws.com/icon/1733391545129.png",
});

export default constants;
